

# Genome = "CCGCATGCTAACACTCGCACCCATGAGCCGCCCGTGCTCCCATACTGCAACTTTGGATAGATACCAAGTTTGGTCGTACGAATCGGGAGTTGCAAACCGTAGGCCGTACGAGTATTATCGCAAACTTTGGGGTTTGGTTTCCCCTCCGCACAGGAGGGCCTTAGGCTGATTTCAGGTTGCAGGGTTTCGTGTGTCGCCGTGTCCCGGGTTTGGCGTGTCCCGGCGGGCGTCGTGTCCCGGTAGCGTGCGTGTCCCGCGTGTCCCGGCCGCCAAGTTCCGGTCCGAACTTCGTTCGCTCGATCAACAACCCAACCCCTATCAACAACCCAATCAACAACCCTTTTGTCCGATAAGTTCACGGTCGGCGAGTTTCGCAACGGGGCGAGTTTCGCGGCGAGTTTCCTGGCGAGTTTCGAGTTTCCGCTCATTCCTGGCGAGTTTCGCCTGGTAGTCTCGCTCATTCCTCTGTTCATCGCGCTTCATCATTCCTCATTCCTCCATTCATTCCTCTGCCTCTGACGAGATTCCAGGCTAAAACGAGATTCATTCGCAGGCTGCGTGACTTCGGCTGGCTTTTAATGATAAACGAAACGAGATTCATTCAACGAGATTCGATAGAAGATACGAGGAACCTCCAGTGTACAGGCCGGAATCTTTTTTGCGCAGGCCGTGCAGAGGCACGCTGCCCTCTCAACTCCAAGGGAATGAGCCCACATCCCTTCGAGTTACGTCGAACGGGAAAAGGACTCATCTTCTGGTTAGAGACTAGTGCGCGCACAACGCAGCAGTAGTTCAACGGCCCTGGAACCAGGAGGGTAGAAAGGCCAGGGGCGATGATGGAAGGGAACTCGTGTGACGGGAATGAATTCTGCACCGTCGCTTTAGTAATTACGCACTTGCACTATCCCCGCAGCTACTGGGACCTGGGACCTCGAGTATGTAATACTGGGACCTGGGACCTGGTACTGGGACCTGTACTGGGACCCATACTGGGACCGCCACCATGTGGATCGAATTCCTAGACCGTTCTTACTATGCCGTCGCGAGCGGTCAGCTGGGTAATCTCGAACCTGGACCTGGCAGAGGCAGAGGTGAATGGTAATCCACTCAGTTATGAGACTACCTGGCAGAACAGAAGACGCTGACCTGGCAGATGCGAGATGCTCGGAGGACGTCTTGGGAAATTGCAAACGCTATGCAAACGCTACGCTAGCTATACGGGGGCTGCATATTAACTGCAAACGCTCAAACGCTGCCATGCAAACGCTTAATGCGCCTGACAACTCGATCCAGGCACCTTGTGATTGGAAAGGAACAGGTCTGCCACCAATCCTCTCACTCTAATCTAGGAGACAGACCATTCGCTACGGTACCTAGACGTAGATAGGGTGTCTACAGGAACGATCCGCACTCATGACCGCAAGCGCATGCTTAGCACCATCATCAAGAGAGATCATCACATCATCAAGTTGTCTGACACATCATCAAGCAACTTGACACAGCCCGCCAACTAAAACTTGACACAGAAAAACTTGACACAGAGACCAGTGAGCCAAAAAATGTTACTTAACTTGACACAACTTGACACTCCGATCTCCACCATCGCTTCGGATGAAAGAACTATTCGCACCCTGCAACCAACGGCAGGAAGTCACACACGCATAATTGAAGGGTGCTTGTCCTACATCTAGCCCTTGAAGGACCGCCAGAGTCCTTCATGTGGGCGGTCCCAAGTTCAGATCTCTAGACTTCGACACTTCTTACGCACAGCCTGAAGCCGTGGTGAGAGACTTGAGGTTCCTTCACCTTGGCATTGGCCCTCTCATGTCGGCGACCTTTTTCGATCAACCTACACATGGCGCCGTGTGCGCGTACGCTTTGGAAGGGCGAATACCGGGACAAGTACGGGTGGAAGATCCTAGCGTTCTACATCTGTTAATTCCTTACATGTGGTTCGGCGTTTAGTTCTCCTATTAGATGTTGCGAGCAGTGTGACGGGC"
# k = 10
# L = 100 
# t = 4

with open("./Genomes_data/E_coli.txt", "r") as file:
    Genome = file.read()
k = 9
L = 500
t = 3

# Clumps, patterns k that appear more or equal t times in window L 
def FrequencyTable(Text, k):
    freq = {}
    n = len(Text)
    for i in range(n - k + 1):
        pattern = Text[i:i+k]
        freq[pattern] = freq.get(pattern, 0) + 1
    return freq

def FindClumps(Genome, k, L, t):
    patterns = set()  
    n = len(Genome)
    
    for i in range(n - L + 1):
        window = Genome[i:i+L]  
        freqMap = FrequencyTable(window, k)
        
        for pattern, count in freqMap.items():
            if count >= t:
                patterns.add(pattern)
    
    return patterns


result = FindClumps(Genome, k, L, t)
print(" ".join(sorted(result)))